module gx4000_plus_asic(
input logic clk16,input logic rst_n,input logic page_enable,input logic [15:0] cpu_addr,input logic cpu_read,input logic cpu_write,input logic [7:0] cpu_wdata,output logic cpu_hit,output logic [7:0] cpu_rdata,input logic classic_palette_we,input logic [4:0] classic_palette_index,input logic [11:0] classic_palette_rgb,input logic [3:0] base_pen,input logic base_border,input logic [9:0] active_x,input logic [7:0] compare_line,input logic hsync,input logic int_ack,input logic raster_reset,output logic [7:0] pri,output logic [7:0] splt,output logic [13:0] ssa,output logic [7:0] sscr,output logic [7:0] ivr,output logic raster_irq_pending,output logic raster_irq_event,output logic [3:0] video_r,output logic [3:0] video_g,output logic [3:0] video_b);
(* ram_style="block" *) logic [3:0] sprite_ram[0:4095];logic [15:0] sprite_x[0:15],sprite_y[0:15];logic [3:0] sprite_mag[0:15];logic [11:0] palette[0:31];integer i;
wire sprite_ram_sel=(cpu_addr>=16'h4000)&&(cpu_addr<=16'h4fff),sprite_attr_sel=(cpu_addr>=16'h6000)&&(cpu_addr<=16'h607f),palette_sel=(cpu_addr>=16'h6400)&&(cpu_addr<=16'h643f),misc_sel=(cpu_addr>=16'h6800)&&(cpu_addr<=16'h6807);assign cpu_hit=page_enable&&(sprite_ram_sel||sprite_attr_sel||palette_sel||misc_sel);logic [3:0] attr_sprite;logic [2:0] attr_off;logic [4:0] palette_no;assign attr_sprite=cpu_addr[6:3];assign attr_off=cpu_addr[2:0];assign palette_no=cpu_addr[5:1];
always_comb begin cpu_rdata=8'hff;if(page_enable&&cpu_read)begin if(sprite_ram_sel)cpu_rdata={4'h0,sprite_ram[cpu_addr[11:0]]};else if(sprite_attr_sel)case(attr_off)0:cpu_rdata=sprite_x[attr_sprite][7:0];1:cpu_rdata=sprite_x[attr_sprite][15:8];2:cpu_rdata=sprite_y[attr_sprite][7:0];3:cpu_rdata=sprite_y[attr_sprite][15:8];default:cpu_rdata=8'hff;endcase else if(palette_sel)cpu_rdata=!cpu_addr[0]?{palette[palette_no][11:8],palette[palette_no][3:0]}:{4'h0,palette[palette_no][7:4]};end end
logic hsync_d,raster_delay_active;logic [7:0] raster_delay_count;always_ff @(posedge clk16 or negedge rst_n)begin if(!rst_n)begin hsync_d<=0;raster_delay_active<=0;raster_delay_count<=0;raster_irq_pending<=0;raster_irq_event<=0;end else begin hsync_d<=hsync;raster_irq_event<=0;if(!hsync_d&&hsync&&(pri!=0)&&(compare_line==pri))begin raster_delay_active<=1;raster_delay_count<=0;end else if(raster_delay_active)begin if(raster_delay_count==159)begin raster_delay_active<=0;raster_irq_pending<=1;raster_irq_event<=1;end else raster_delay_count<=raster_delay_count+1'b1;end if(int_ack||raster_reset)raster_irq_pending<=0;end end
always_ff @(posedge clk16 or negedge rst_n)begin if(!rst_n)begin pri<=0;splt<=0;ssa<=0;sscr<=0;ivr<=0;for(i=0;i<16;i=i+1)begin sprite_x[i]<=0;sprite_y[i]<=0;sprite_mag[i]<=0;end for(i=0;i<32;i=i+1)palette[i]<=0;end else begin if(classic_palette_we&&classic_palette_index<=16)palette[classic_palette_index]<=classic_palette_rgb;if(page_enable&&cpu_write)begin if(sprite_ram_sel)sprite_ram[cpu_addr[11:0]]<=cpu_wdata[3:0];else if(sprite_attr_sel)case(attr_off)0:sprite_x[attr_sprite][7:0]<=cpu_wdata;1:sprite_x[attr_sprite][15:8]<=cpu_wdata;2:sprite_y[attr_sprite][7:0]<=cpu_wdata;3:sprite_y[attr_sprite][15:8]<=cpu_wdata;4:sprite_mag[attr_sprite]<=cpu_wdata[3:0];default:;endcase else if(palette_sel)begin if(!cpu_addr[0])begin palette[palette_no][11:8]<=cpu_wdata[7:4];palette[palette_no][3:0]<=cpu_wdata[3:0];end else palette[palette_no][7:4]<=cpu_wdata[3:0];end else if(misc_sel)case(cpu_addr[2:0])0:pri<=cpu_wdata;1:splt<=cpu_wdata;2:ssa[13:8]<=cpu_wdata[5:0];3:ssa[7:0]<=cpu_wdata;4:sscr<=cpu_wdata;5:ivr<=cpu_wdata;default:;endcase end end end
logic [11:0] final_rgb;logic [3:0] sprite_pixel;logic sprite_found;integer s;integer signed px,py,sxpos,sypos,dx,dy;integer xscale,yscale,xshift,yshift,sxpix,sypix,ram_index;
always_comb begin sprite_found=0;sprite_pixel=0;if(!base_border)begin px=$signed({1'b0,active_x});py=$signed({1'b0,compare_line});for(s=0;s<16;s=s+1)begin if(!sprite_found&&(sprite_mag[s][3:2]!=0)&&(sprite_mag[s][1:0]!=0))begin sxpos=$signed(sprite_x[s][9:0]);sypos=$signed(sprite_y[s][8:0]);case(sprite_mag[s][3:2])1:begin xscale=1;xshift=0;end 2:begin xscale=2;xshift=1;end default:begin xscale=4;xshift=2;end endcase case(sprite_mag[s][1:0])1:begin yscale=1;yshift=0;end 2:begin yscale=2;yshift=1;end default:begin yscale=4;yshift=2;end endcase dx=px-sxpos;dy=py-sypos;if((dx>=0)&&(dy>=0)&&(dx<16*xscale)&&(dy<16*yscale))begin sxpix=dx>>>xshift;sypix=dy>>>yshift;ram_index=(s<<8)+(sypix<<4)+sxpix;if(sprite_ram[ram_index]!=0)begin sprite_pixel=sprite_ram[ram_index];sprite_found=1;end end end end end if(base_border)final_rgb=palette[16];else if(sprite_found)final_rgb=palette[16+sprite_pixel];else final_rgb=palette[{1'b0,base_pen}];video_r=final_rgb[11:8];video_g=final_rgb[7:4];video_b=final_rgb[3:0];end
endmodule
