// 27 MHz Tang Nano 20K board clock.
create_clock -name clk27 -period 37.037 -waveform {0 18.5185} [get_ports {clk27}]
// Phase-2 32/16 MHz clocks are generated by u_phase2's rPLL/divider.
// HDMI 135/27 MHz clocks are generated by u_hdmi_pll/u_hdmi_clkdiv.
create_clock -name hdmi_pixel_clk -period 37.037 -waveform {0 18.5185} [get_pins {u_hdmi_clkdiv/CLKOUT}]
